# Google OAuth
GOOGLE_CLIENT_ID: "612054615143-74i6mnnb403dic4an5rhm7qp5k6daqu4.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET: "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"

# Naver OAuth
NAVER_CLIENT_ID: "hZRYktnbw3SflkAAiF_3"
NAVER_CLIENT_SECRET: "LtrcilA2CF"

# Gmail SMTP
GMAIL_USERNAME: "sml940317@gmail.com"
GMAIL_APP_PASSWORD: "hley oeso jmze dhoz"

# Database Credentials
DB_USERNAME: "root"
DB_PASSWORD: "1234"

JWT_SECRET_KEY: "5700d328b5c4ead75f1a34a4531af6671986371432d9bdf3c7cc2bdd30377f8859110d1181d88901"