server:
  port: 8080

spring:
  application:
    name: rentex

  # 민감정보 분리 (ID/SECRET 등)
  config:
    import: optional:classpath:application-secret.properties,optional:file:./application-secret.properties

  datasource:
    url: jdbc:mariadb://localhost:3307/rentex
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:init/rentex.sql

  web:
    resources:
      static-locations:
        - classpath:/static/           # 정적 리소스 (빌드 시 포함된 기본 이미지)
        - file:${file.upload-dir}/     # 업로드 파일 (외부 경로)

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  # ==========================
  # OAuth2 (Naver)
  # ==========================
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}         # application-secret.properties에서 주입
            client-secret: ${NAVER_CLIENT_SECRET} # application-secret.properties에서 주입
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response  # 네이버는 response 아래에 프로필이 들어옵니다

# ===================================
# 업로드 파일 저장 경로
# ===================================
file:
  upload-dir: ./uploads
  # AWS 배포 시: /home/ubuntu/rentex/uploads 로 변경

# ===================================
# 프론트엔드 도메인 주소 (CORS 허용)
# ===================================
app:
  frontend-url: http://localhost:3000
  # AWS 배포 시: https://rentex.site 같은 실제 프론트 주소로 변경

## 테스트용 옵션 예시
# debug: true
# logging:
#   level:
#     org.springframework.boot.context.config: TRACE
#     org.springframework.core.env: TRACE
