server:
  port: 8080

spring:
  application:
    name: rentex

  # ✅ secret 파일을 classpath와 로컬 파일 둘 다에서 찾게 설정
  config:
    import: optional:classpath:application-secret.properties,optional:file:./application-secret.properties

  datasource:
    url: jdbc:mariadb://localhost:3307/rentex
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      schema-locations: classpath:init/rentex.sql

  web:
    resources:
      static-locations: classpath:/static/, file:///C:/rentex/

# 🔽 spring 바깥 최상단에 선언, 배포할 때 https://rentex.com 이런식을 변경
app:
  frontend-url: http://localhost:3000
